version: '3.8'

services:
  db:
    image: postgres:13
    container_name: mental_health_db_v2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: u_pick_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: mental_health_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:u_pick_password@db:5432/postgres
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0  # This is important to make Flask listen on all interfaces
      FLASK_RUN_PORT: 5000
    volumes:
      - .:/app

volumes:
  pgdata:
